# Generated by Django 5.0.1 on 2025-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='shared_playlist',
        ),
        migrations.RemoveField(
            model_name='message',
            name='shared_song',
        ),
    ]
