# Generated by Django 5.0.1 on 2025-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='shared_playlist',
        ),
        migrations.RemoveField(
            model_name='message',
            name='shared_song',
        ),
        migrations.AlterUniqueTogether(
            name='offlinedownload',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='offlinedownload',
            name='song',
        ),
        migrations.RemoveField(
            model_name='offlinedownload',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='song',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='OfflineDownload',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
